### ISSUE TITLE
 Is it possible to sweep in all sheets areas?

### ISSUE THREAD

**Issue by wahyutaufik** [atsutopia/vue-swipeable-bottom-sheet#6]
I saw at [react-swipeable-bottom-sheet demo](https://manufont.github.io/react-swipeable-bottom-sheet/index.html), that it could be swiped in the sheet area. Can it be like that?

**Comment by techuila** [comment]
Just made a merge request for this feature, still waiting for the approval. [#13 ](https://github.com/atsutopia/vue-swipeable-bottom-sheet/pull/13)

![TRIMVIDEO](https://user-images.githubusercontent.com/15911107/93042655-37c41480-f682-11ea-90eb-a9a5b2361405.gif)

**Comment by axtutuu** [comment]
@techuila thanks ;)
